version: '3.3'

services:
  api:
    container_name: bfl_api
    build: ./server
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=development
      # - ARANGO_HOST=db
    depends_on:
      - db

  db:
    container_name: bfl_db
    image: arangodb:3.7.2
    ports:
      - '8529:8529'
    environment:
      - ARANGO_ROOT_PASSWORD=bfl
